document.getElementById('tx-date').value = localIsoDate(new Date());
renderMainCategoriesForm();
initTheme();
initOnboarding();
initPanelHeaders();
initOverlayCloseIcons();
initData();
scheduleMarketPriceRefresh();
registerServiceWorker();
initNotifications();
checkModuleSplitThreshold();
